# Generated by Django 3.1 on 2020-08-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_content', models.TextField()),
                ('article_publise_time', models.DateField()),
                ('article_category', models.CharField(max_length=200)),
                ('article_tags', models.CharField(max_length=200)),
            ],
        ),
    ]
